# Generated by Django 6.0 on 2026-01-06 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_backlogs', models.IntegerField()),
                ('branches_allowed', models.JSONField()),
                ('deadline', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile')),
            ],
        ),
    ]
